<a href="https://colab.research.google.com/github/melissa-aguiar/DeepLearning/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section 1 of:

https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/

https://deeplearningcourses.com/c/deep-learning-prerequisites-the-numpy-stack-in-python

## Arrays vs Lists

In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4) # doesn't work

AttributeError: ignored

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5]) # doesn't work

ValueError: ignored

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [ ]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
b.dot(a)

11

In [ ]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [ ]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [ ]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [ ]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 61.40886407012087


## Matrices

In [ ]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [ ]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems

In [ ]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [ ]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.7581150038421872

In [ ]:
np.random.random((2, 3))

array([[0.03284802, 0.83250625, 0.2914984 ],
       [0.03998929, 0.85275735, 0.31078009]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.97730916,  0.05594193, -2.46231718],
       [ 0.75246035, -1.46678342, -0.97568316]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

0.0008930280270368496

In [ ]:
np.mean(R)

In [ ]:
R.var()

1.0276856891466102

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0)

array([-0.00671182, -0.0086458 , -0.01834377])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 0.98396137,  0.00432999,  0.01031152],
       [ 0.00432999,  0.99723915, -0.004402  ],
       [ 0.01031152, -0.004402  ,  0.99895114]])

In [ ]:
np.cov(R, rowvar=False)

array([[ 0.98396137,  0.00432999,  0.01031152],
       [ 0.00432999,  0.99723915, -0.004402  ],
       [ 0.01031152, -0.004402  ,  0.99895114]])

In [ ]:
np.random.randint(0, 10, size=(3, 3))

array([[6, 1, 2],
       [9, 7, 8],
       [4, 8, 1]])

In [ ]:
np.random.choice(10, size=(3, 3))

array([[3, 2, 5],
       [7, 8, 4],
       [6, 4, 1]])